### ISSUE TITLE
Add examples for sugar skull

### ISSUE THREAD

**Issue by schelhorn** [awentzonline/image-analogies#18]
Could you please add examples also for generating the sugar skull analogy, and provide a brief explanation in the README for why here are three input images required compared to the two input images for the arch example? Thank you!

**Comment by awentzonline** [comment]
I've added some example scripts which show some reasonable settings: https://github.com/awentzonline/image-analogies/tree/master/examples

The script always requires three images for input (A, A', B)  The A and A' are style images, B is the content image. First, B is reconstructed by finding the best match for it in A, but then actually using the corresponding patch from A'. So A acts like a bridge between the styles of B and A'. So in the case of the sugar skull, A is a blurred version of A' (the skull) so that it more closely matches the distribution of pixels in the photograph which is Image B (i.e. Steve B). A and A' can be the exact same image and you'll still get the benefit of mapping B into the style of A'. Texture by numbers (e.g. the arch) is a more transparent example of mapping B into A' via A.

**Comment by schelhorn** [comment]
Great, thanks!
